src/WMS/WMS/urls.py
from django.contrib import admin
from django.urls import re_path as url
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from bases.views import index
from django.conf.urls import include

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^users/', include('users.urls')),
    url(r'^stock/', include('stock.urls')),
    url('admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/WMS/stock/urls.py
from django.urls import re_path as url
from stock.views import excel_import, search, location_list, call_location, bin_list, item_import, wo_import, wo_search, \
    call_wo_item_check

urlpatterns = [
    url(r'^wo_search/', wo_search, name='wo_search'),
    url(r'^wo_import/', wo_import, name='wo_import'),
    url(r'^item_import/', item_import, name='item_import'),
    url(r'^import/', excel_import, name='stock_import'),
    url(r'^search/', search, name='stock_search'),
    url(r'^location/', location_list, name='location_list'),
    url(r'^bin/(?P<storage>\w+)/(?P<location>\w+)', bin_list, name='bin_list'),
    url(r'^call_location/', call_location, name='call_location'),
    url(r'^call_wo_item_check/', call_wo_item_check, name='call_wo_item_check'),
]

src/WMS/stock/models.py
from django.db import models
from django.conf import settings
from django.utils.html import format_html

class Access_Point(models.Model):
    point_code = models.CharField(max_length=6, primary_key=True)
    point_name = models.CharField(max_length=50, blank=False, null=False)
    desc = models.CharField(max_length=200, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='access_point_update_by')

    def __str__(self):
        return self.point_name


class Storage_Type(models.Model):
    type_code = models.CharField(max_length=6, primary_key=True)
    type_name = models.CharField(max_length=50, blank=False, null=False)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='storage_type_update_by')

    def __str__(self):
        return self.type_name


class Storage(models.Model):
    storage_code = models.CharField(max_length=6, primary_key=True)
    type = models.ForeignKey(Storage_Type, related_name='storage_type', on_delete=models.DO_NOTHING)
    desc = models.CharField(max_length=200, blank=True, null=True)
    ip_addr = models.CharField(max_length=15, blank=True, null=True)
    lift = models.CharField(max_length=1, blank=True, null=True)
    access_point = models.ManyToManyField(Access_Point, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='storage_update_by')
    enable = models.CharField(max_length=1, blank=True, null=True)

    def __str__(self):
        return self.desc


class Location(models.Model):
    storage = models.ForeignKey(Storage, related_name='storage_location', on_delete=models.DO_NOTHING)
    location_code = models.CharField(max_length=10, primary_key=True)
    location_name = models.CharField(max_length=20, blank=False, null=False)
    desc = models.CharField(max_length=200, blank=True, null=True)
    mach_location_code = models.CharField(max_length=2, blank=True, null=True)
    type = models.ForeignKey(Storage_Type, related_name='location_type', on_delete=models.DO_NOTHING)
    enable = models.CharField(max_length=1, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='location_update_by')

    def __str__(self):
        return self.desc


class Bin(models.Model):
    location = models.ForeignKey(Location, related_name='location_bin', on_delete=models.DO_NOTHING)
    bin_code = models.CharField(max_length=20, primary_key=True)
    bin_name = models.CharField(max_length=200, blank=True, null=True)
    enable = models.CharField(max_length=1, blank=True, null=True)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='bin_update_by')

    def __str__(self):
        return self.desc


class Item(models.Model):
    item_code = models.CharField(max_length=10, primary_key=True)
    desc = models.CharField(max_length=200, blank=True, null=True)
    bin = models.ManyToManyField(Bin)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='item_update_by')

    def __str__(self):
        return self.desc


class Item_attachment(models.Model):
    item = models.ForeignKey('Item', related_name='item_pics', on_delete=models.CASCADE)
    files = models.FileField(upload_to='uploads/picture/')
    description = models.CharField(max_length=50, blank=True)
    create_at = models.DateTimeField(auto_now_add=True, editable=True)  # 建立日期
    create_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='pic_create_by')  # 建立者


class WO(models.Model):
    wo_no = models.CharField(max_length=10, blank=False, null=False)
    item = models.ForeignKey('Item', related_name='wo_item', on_delete=models.DO_NOTHING)
    qty = models.IntegerField(default=0)
    checked = models.BooleanField(default=False)
    update_at = models.DateTimeField(auto_now=True, null=True)
    update_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING,
                                  related_name='wo_update_by')

    def __str__(self):
        return self.wo_no

src/WMS/stock/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, HTML, Button, Submit


class SearchForm(forms.Form):
    wo_no = forms.CharField(required=False, label="工單號碼")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.form_show_errors = True

        self.helper.layout = Layout(
            Div(
                Div('wo_no', css_class='col-md-10'),
                Div(Submit('search', '查詢', css_class='btn btn-info'),
                    css_class='col-md-2 d-flex align-items-center search_btn_fix pt-3'),
                css_class='row'),
        )

src/WMS/stock/views.py
import json

import openpyxl
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from suds import client
from django.http import JsonResponse
from WMS.settings.base import HANEL_WS
from stock.forms import SearchForm
from stock.models import Storage_Type, Storage, Location, Bin, Item, WO


@login_required
def wo_search(request):
    if request.method == 'POST':
        wo_no = str(request.POST.get('wo_no')).strip()
        items = WO.objects.filter(wo_no=wo_no).all().order_by('item__item_code')
        for item in items:
            print(item.item.item_code+"   "+str(item.checked))
        #search_form = SearchForm(initial={'wo_no': wo_no})
        search_form = SearchForm()
    else:
        search_form = SearchForm()
    return render(request, 'stock/wo_search.html', locals())


@login_required
def wo_import(request):
    if request.method == 'POST':
        excel_file = request.FILES.get('files1')
        wo_del_list = []
        if excel_file:
            wb = openpyxl.load_workbook(excel_file)
            sheet = wb.worksheets[0]
            for index in range(1, 30):
                if sheet.cell(row=1, column=index).value == "物料":
                    item_index = index
                elif sheet.cell(row=1, column=index).value == "MvT":
                    mvt_index = index
                elif sheet.cell(row=1, column=index).value == "表頭內文":
                    wo_index = index
                elif sheet.cell(row=1, column=index).value == "SLoc":
                    loc_index = index
                elif sheet.cell(row=1, column=index).value == "數量":
                    qty_index = index


            for iRow in range(2, sheet.max_row + 1):
                try:
                    wo_no = sheet.cell(row=iRow, column=wo_index).value
                    wo = WO.objects.filter(wo_no=wo_no)
                    if wo and wo_no not in wo_del_list:
                        wo.delete()
                        wo_del_list.append(wo_no)
                    mvt = str(sheet.cell(row=iRow, column=mvt_index).value)
                    loc = str(sheet.cell(row=iRow, column=loc_index).value)
                    item_code = str(sheet.cell(row=iRow, column=item_index).value)
                    item = Item.objects.get(item_code=item_code)
                    qty = sheet.cell(row=iRow, column=qty_index).value

                    if mvt == "311" and loc == "0030":
                        wo = WO.objects.create(wo_no=wo_no, item=item,
                                               qty=qty, update_by=request.user)
                        print("{wo_no}  {item_code}".format(wo_no=wo_no, item_code=item_code))

                except Exception as e:
                    print(e)

    return render(request, 'stock/wo_import.html', locals())


@login_required
def item_import(request):
    if request.method == 'POST':
        excel_file = request.FILES.get('files1')
        if excel_file:
            wb = openpyxl.load_workbook(excel_file)
            sheet = wb.worksheets[0]
            for iRow in range(2, sheet.max_row + 1):
                try:
                    item_code = str(sheet.cell(row=iRow, column=1).value)
                    if len(item_code) == 10:
                        desc = sheet.cell(row=iRow, column=2).value
                        new_bin = sheet.cell(row=iRow, column=7).value
                        new_bin = Bin.objects.get(bin_code=new_bin)
                        item = Item.objects.update_or_create(item_code=item_code, defaults={'desc': desc, 'update_by': request.user})
                        item = Item.objects.get(item_code=item_code)
                        bins = item.bin.all()
                        if new_bin not in bins:
                            item.bin.add(new_bin)
                except Exception as e:
                    print(e)

    return render(request, 'stock/import.html', locals())

@login_required
def excel_import(request):
    if request.method == 'POST':
        excel_file = request.FILES.get('files1')
        if excel_file:
            try:
                wb = openpyxl.load_workbook(excel_file)
                for sheet in wb.worksheets:
                    print(sheet)
                    # if sheet.title == "Storage":
                    #     for iRow in range(2, sheet.max_row + 1):
                    #         storage_code = sheet.cell(row=iRow, column=1).value
                    #         type = sheet.cell(row=iRow, column=2).value
                    #         type = Storage_Type.objects.get(type_code=type)
                    #         desc = sheet.cell(row=iRow, column=3).value
                    #         ip_addr = sheet.cell(row=iRow, column=4).value
                    #         lift = sheet.cell(row=iRow, column=5).value
                    #         access_point = sheet.cell(row=iRow, column=6).value
                    #         enable = sheet.cell(row=iRow, column=7).value
                    #         storage = Storage.objects.update_or_create(storage_code=storage_code,
                    #                                                    defaults={'type': type, 'desc': desc,
                    #                                                              'ip_addr': ip_addr,
                    #                                                              'lift': lift,
                    #                                                              'access_point': access_point,
                    #                                                              'update_by': request.user,
                    #                                                              'enable': enable, })
                    if sheet.title == "Location":
                        for iRow in range(2, sheet.max_row + 1):
                            storage = sheet.cell(row=iRow, column=1).value
                            storage = Storage.objects.get(storage_code=storage)
                            location_code = sheet.cell(row=iRow, column=2).value
                            location_name = sheet.cell(row=iRow, column=3).value
                            mach_location_code = sheet.cell(row=iRow, column=4).value
                            type = sheet.cell(row=iRow, column=5).value
                            type = Storage_Type.objects.get(type_code=type)
                            desc = sheet.cell(row=iRow, column=6).value
                            enable = sheet.cell(row=iRow, column=7).value
                            location = Location.objects.update_or_create(storage=storage, location_code=location_code,
                                                                 defaults={'location_name':location_name, 'mach_location_code':mach_location_code,
                                                                         'type':type, 'desc':desc, 'enable':enable, 'update_by':request.user})
                    elif sheet.title == "Bin":
                        for iRow in range(2, sheet.max_row + 1):
                            bin_code = sheet.cell(row=iRow, column=1).value
                            bin_name = sheet.cell(row=iRow, column=2).value
                            location_code = sheet.cell(row=iRow, column=4).value
                            location = Location.objects.get(location_code=location_code)
                            desc = sheet.cell(row=iRow, column=5).value
                            enable = sheet.cell(row=iRow, column=6).value
                            bin = Bin.objects.update_or_create(location=location, bin_code=bin_code,
                                                                 defaults={'bin_name': bin_name, 'enable': enable,
                                                                    'update_by': request.user})
            except Exception as e:
                print(e)


    return render(request, 'stock/import.html', locals())



@login_required
def search(request):
    storages = Storage.objects.all()
    return render(request, 'stock/storage.html', locals())


@login_required
def location_list(request):
    if request.method == 'POST':
        storage_code = request.POST.get('pk')
        storage = Storage.objects.get(storage_code=storage_code)
        locations = Location.objects.filter(storage=storage).all()
    return render(request, 'stock/location.html', locals())


@login_required
def bin_list(request, storage, location):
    bins = Bin.objects.filter(location=location).all()
    return render(request, 'stock/bin.html', locals())


@csrf_exempt
def call_location(request):
    if request.method == 'POST':
        try:
            storage = request.POST.get('storage')
            location = request.POST.get('location')
            lift = request.POST.get('lift')
            access_point = request.POST.get('access_point')

            web_s = client.Client(HANEL_WS)
            params = web_s.factory.create("ns2:JobRecordV02")
            params.lift = lift
            params.accessPoint = access_point  # 1:一樓   2:二樓
            params.shelf = location  # 01;02;03
            params.job = '1000727161'
            res = web_s.service.sendJobBufferV02(params)
            result = "DONE"
        except Exception as e:
            result = "ERROR"

    return JsonResponse(result, safe=False)


@csrf_exempt
def call_wo_item_check(request):
    if request.method == 'POST':
        try:
            pk = request.POST.get('pk')
            item_checked = request.POST.get('item_checked')
            wo_item = WO.objects.get(pk=pk)
            wo_item.checked = json.loads(item_checked)
            wo_item.save()
            result = "DONE"
        except Exception as e:
            result = "ERROR"

    return JsonResponse(result, safe=False)

src/WMS/stock/templates/stock/base.html
{% extends 'bases/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block head %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
{% endblock %}
{% block title %}
Excel
{% endblock %}
{% block breadcrumb %}

{% endblock %}
{% block container %}
<div class="card-header">
    <div class="row">
        <div class="col">
            {% block menu %}
            {% endblock menu %}
            <a href="{% url 'wo_import' %}" class="btn btn-info">工單匯入</a>
            <a href="{% url 'wo_search' %}" class="btn btn-info">工單查詢</a>
            {% if user.is_authenticated %}
                <a href="{% url 'stock_search' %}" class="btn btn-info">儲位叫車</a>
                <a href="{% url 'stock_import' %}" class="btn btn-info">主檔匯入</a>
            {% endif %}
        </div>
        {% if user.is_authenticated %}
        <div class="ml-md-auto">
            <a class="btn btn-info" href="{% url 'logout' %}" role="button"><i class="fas fa-sign-out-alt"></i>{% trans "logout" %} ({{ user.username }})</a>
        </div>
        {% endif %}
    </div>
</div>

{% block content %}
{% endblock content %}
{% endblock %}
{% block base_js %}
<script>
var error_msg = "{{ error_msg }}";
if(error_msg.length>0) {
    alert(error_msg);
}
</script>
{% endblock base_js %}

src/WMS/stock/templates/stock/import.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
    $(document).ready(function() {
        $("#import_form").submit(function(e) {
            $("body").loading();
        });
    });

</script>
<!-- jquery-loading v1.3.0 -->
<link href="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
{% endblock js %}
{% block content %}

<div class="pt-3">
    <ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="import-tab" data-toggle="pill" href="#import" role="tab" aria-controls="import" aria-selected="true">匯入資料</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="upload-record-tab" data-toggle="pill" href="#upload-record" role="tab" aria-controls="upload-record" aria-selected="false">匯入紀錄</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="import" role="tabpanel" aria-labelledby="import-tab">
            <div class="p-4">
            <form action="" method="post" class="form-group font-weight-bold align-middle" id="import_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    <div>請選擇Template檔案(*.xlsx)
                        <a href="{% static "templates/stock/template.xlsx" %}" target="_blank">下載範本檔</a>
                    </div>
                    <div class="row">
                        <div id="div_id_files" class="form-group">
                            <input name="files1" accept=".xls,.xlsx" class="clearablefileinput" id="id_files" type="file">
                            <button type="submit" class="btn btn-primary" id="send">上傳</button>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>
        <div class="tab-pane fade" id="upload-record" role="tabpanel" aria-labelledby="upload-record-tab">
            <div class="p-3">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">上傳時間</th>
                        <th width="20%">上傳者</th>
                        <th width="30%">檔案名稱</th>
                        <th width="20%">下載</th>
                    </tr>
                    {% for coois in cooises %}
                    <tr>
                        <td>{{ coois.create_at }}</td>
                        <td>{{ coois.create_by }}</td>
                        <td>{{ coois.file_name }}</td>
                        <td><a href="{{ coois.file_url }}" class="btn btn-light">下載</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

src/WMS/stock/templates/stock/wo_import.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block js %}
<script>
    $(document).ready(function() {
        $("#import_form").submit(function(e) {
            $("body").loading();
        });
    });

</script>
<!-- jquery-loading v1.3.0 -->
<link href="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
{% endblock js %}
{% block content %}

<div class="pt-3">
    <ul class="nav nav-tabs mb-3" id="pills-tab" role="tablist">
      <li class="nav-item">
        <a class="nav-link active" id="import-tab" data-toggle="pill" href="#import" role="tab" aria-controls="import" aria-selected="true">匯入資料</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="upload-record-tab" data-toggle="pill" href="#upload-record" role="tab" aria-controls="upload-record" aria-selected="false">匯入紀錄</a>
      </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="import" role="tabpanel" aria-labelledby="import-tab">
            <div class="p-4">
            <form action="{% url 'wo_import' %}" method="post" class="form-group font-weight-bold align-middle" id="import_form" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-body">
                    <div>請選擇WO Template檔案(*.xlsx)
                        <a href="{% static "templates/stock/mb51_template.xlsx" %}" target="_blank">下載範本檔</a>
                    </div>
                    <div class="row">
                        <div id="div_id_files" class="form-group">
                            <input name="files1" accept=".xls,.xlsx" class="clearablefileinput" id="id_files" type="file">
                            <button type="submit" class="btn btn-primary" id="send">上傳</button>
                        </div>
                    </div>
                </div>
            </form>
            </div>
        </div>
        <div class="tab-pane fade" id="upload-record" role="tabpanel" aria-labelledby="upload-record-tab">
            <div class="p-3">
                <table class="table table-bordered table-striped">
                    <tr>
                        <th width="20%">上傳時間</th>
                        <th width="20%">上傳者</th>
                        <th width="30%">檔案名稱</th>
                        <th width="20%">下載</th>
                    </tr>
                    {% for coois in cooises %}
                    <tr>
                        <td>{{ coois.create_at }}</td>
                        <td>{{ coois.create_by }}</td>
                        <td>{{ coois.file_name }}</td>
                        <td><a href="{{ coois.file_url }}" class="btn btn-light">下載</a></td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
            {{ message }}
        </li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock %}

src/WMS/stock/templates/stock/wo_search.html
{% extends 'stock/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block css%}
<style>
    #location_data > table > thead > tr > th {
        cursor: pointer;
    }

    .data-row {
        cursor: pointer;
    }
</style>
{% endblock css %}
{% block js %}
<link href="{% static '/base/css/toggle-switchy.css' %}" rel="stylesheet">
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
<!-- jquery-loading v1.3.0 -->
<link href="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.css" rel="stylesheet" />
<script src="https://cdn.jsdelivr.net/npm/jquery-easy-loading@1.3.0/dist/jquery.loading.min.js"></script>
<script>

    call = function(storage, location, lift, access_point) {
        $.ajax({
            type: "POST",
            dataType: 'json',
            url: "{% url 'call_location' %}",
            data: {'storage': storage, 'location': location, 'lift': lift, 'access_point': access_point, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText);
            },
            success: function(data) {
                console.log('storage:'+ storage+',location:'+ location+ ',lift' + lift + ',access_point:' + access_point)
                alert(data);
            }
        })
    }

    item_check = function(pk) {
        var item_checked = $("#check_"+pk).prop('checked');
        $.ajax({
            type: "POST",
            dataType: 'json',
            url: "{% url 'call_wo_item_check' %}",
            data: {'pk': pk, 'item_checked': item_checked, 'csrfmiddlewaretoken': '{{csrf_token}}'},
            error: function (jqXHR, textStatus, errorThrown) {
                alert(jqXHR.responseText);
            },
            success: function(data) {
                console.log(data)
            }
        })
    }

    info = function(item_code, desc) {
        $("#item_code").html(item_code);
        $("#desc").html(desc);
    }
</script>
{% endblock js %}
{% block ready %}
$("#id_wo_no").focus();
{% endblock ready %}
{% block content %}
<div class="p-3">
    <div class="p-3">
        <form action="{% url 'wo_search' %}" method="POST">
            {% crispy search_form %}
        </form>
    </div>
    <div class="mb-3 p-2" style="border: 1px solid #dee2e6;text-align: center;font-size: 1.3em">{{ wo_no }}</div>
    <table id="wo_search" class="table table-striped table-bordered table-hover" data-toggle="table">
        <thead>
            <tr class="text-center table-active">
                <th scope="col" class="text-center text-nowrap" style="width: 10%;" data-field="checked" data-sortable="true">狀態</th>
                <th scope="col" class="text-center text-nowrap" style="width: 20%;" data-field="item_code" data-sortable="true">料號</th>
                <th scope="col" class="text-center text-nowrap" style="width: 20%;">說明</th>
                <th scope="col" class="text-center text-nowrap" style="width: 10%;">數量</th>
                <th scope="col" class="text-center text-nowrap" style="width: 20%;" data-field="bin" data-sortable="true">儲格</th>
                <th scope="col" class="text-center text-nowrap" style="width: 20%;"></th>
            </tr>
        </thead>
        <tbody>
            {% for wo_item in items %}
            <tr class="data-row">
                <td>
                    <label class="toggle-switchy" for="check_{{ wo_item.pk }}" data-size="lg">
                      <input type="checkbox" id="check_{{ wo_item.pk }}" onchange="item_check('{{ wo_item.pk }}')" {% if wo_item.checked %}checked{% else %}''{% endif %}>
                      <span class="toggle">
                        <span class="switch"></span>
                      </span>
                    </label>
                <td class="text-center text-nowrap">
                    <a href="#" class="btn btn-light" data-toggle="modal" data-target=".bd-example-modal-lg" onclick="info('{{ wo_item.item.item_code }}', '{{ wo_item.item.desc }}')">{{ wo_item.item.item_code }}</a>
                </td>
                <td class="text-center text-nowrap">{{ wo_item.item.desc }}</td>
                <td class="text-center text-nowrap">{{ wo_item.qty }}</td>
                <td class="text-center text-nowrap">
                    {% for bin in wo_item.item.bin.all %}
                    {{ bin.bin_name }}
                    {% endfor %}
                </td>
                <td class="text-center text-nowrap">
                    {% for point in wo_item.item.bin.first.location.storage.access_point.all %}
                        <button style="width: 100px" type='button' class='btn btn-info' onclick="call('{{ wo_item.storage.storage_code }}','{{ wo_item.location.mach_location_code }}','{{ wo_item.storage.lift }}','{{ point.point_code }}')">{{ point.point_name }}</button>
                    {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<div style="height: 50px;"></div>
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content align-items-center justify-content-center" style="height: 600px;">
        <div id="item_code" class="row" style="font-size: 8em;"></div>
        <div id="desc" class="row h1"></div>
    </div>
  </div>
</div>
{% endblock %}